import '../styles/globals.css';
import { AnimatePresence } from 'framer-motion';
import { ThemeProvider } from 'styled-components';
import Maintheme from '../styles/Maintheme';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Iñaki Lambrechts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence exitBeforeEnter initial={true}>
        <ThemeProvider theme={Maintheme}>
          <Component {...pageProps} />
        </ThemeProvider>
      </AnimatePresence>
    </>
  );
}

export default MyApp
